# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Create Backend .env
      run: |
        cd backend
        echo "PORT=${{ secrets.PORT }}" > .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        
    - name: Create Frontend .env
      run: |
        cd frontend
        echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env
    
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm install
        
    - name: Install Frontend Dependencies and Build
      working-directory: ./frontend
      run: |
        npm install
        npm run build
        
    - name: Restart PM2 Processes
      run: |
        pm2 restart all
        pm2 save
        
    - name: Reload Nginx
      run: |
        sudo systemctl reload nginx
